### ISSUE TITLE
parameter settings

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#11]
- 20 repeats only for d2h measure
- I can only see quantile transformation is picked up quite good amount of times.

# Learner
![learner](https://user-images.githubusercontent.com/3458568/46909017-b8f45900-cef9-11e8-9740-3d1c3b8a2e3c.png)

# Preprocess
![preprocess](https://user-images.githubusercontent.com/3458568/46909019-bb56b300-cef9-11e8-8626-ebbefac0ad47.png)

**Comment by timm** [comment]
Any issue with expressing all the above as percentiles?

**Comment by timm** [comment]
And I reading this  right? Learners are all random choices? Equally likely? Only some biases in some ore processing ?

**Comment by amritbhanu** [comment]
by percentiles you mean, each and every column?

From the results ya looks like. Especially in preprocessor it is bit biased towards, Quantile Transform one.
