### ISSUE TITLE
FFT against Tabu 100 evaluations:

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#12]
## D2h:
- Same numbers as seen for upto 1000 evaluations:

<img width="541" alt="d2h 100" src="https://user-images.githubusercontent.com/3458568/47054289-fae20100-d17e-11e8-8a5b-505626d8df59.png">

## popt20:
- Same numbers as seen for upto 1000 evaluations:
<img width="436" alt="popt20 100" src="https://user-images.githubusercontent.com/3458568/47054321-177e3900-d17f-11e8-8cda-d18078845aba.png">

**Comment by timm** [comment]
so we have a recommendation for a heuristic on how to run all this
