### ISSUE TITLE
Result - D2h - Lower the better

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#3]

**Comment by amritbhanu** [comment]
## Median and IQR for 20 repeats in each iteration

### camel
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/camel_iqr.png)

### Jedit
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/jedit_iqr.png)

### Poi
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/poi_iqr.png)

### log4j
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/log4j_iqr.png)

### synapse
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/synapse_iqr.png)

### velocity
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/velocity_iqr.png)

### xalan
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/xalan_iqr.png)

### xerces
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/xerces_iqr.png)

### ivy
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/ivy_iqr.png)

### lucene
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/lucene_iqr.png)

**Comment by timm** [comment]
this results show much support for your thesis. 0.2 kills it almost instantly while other measures need more samples.

not that If the usual termination is at n=200 then to be 95% confident we can get there, e=0.12 (see below)

log=math.log; c=0.95; e=0.12; n= log(1-c)/log(1-(e^2)); print(n)
n=206
