### ISSUE TITLE
Options being explored

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#4]
## Transformations
- StandardScaler
- MinMaxScaler
- MaxAbsScaler
- RobustScaler(quantile_range=(a, b))
    - a,b=_randint(0,50),_randint(51,100)
- KernelCenterer
- QuantileTransformer(n_quantiles=a, output_distribution=c, subsample=b)
    - a, b = _randint(100, 1000), _randint(1000, 1e5)
    - c=_randchoice(['normal','uniform'])
- Normalizer(norm=a)
    - a = _randchoice(['l1', 'l2','max'])
- Binarizer(threshold=a)
   - a=_randuniform(0,100)

## Learners
- DecisionTreeClassifier(criterion=b, splitter=c, min_samples_split=a)
   - a=_randuniform(0.0,1.0)
   - b=_randchoice(['gini','entropy'])
   - c=_randchoice(['best','random'])
- RandomForestClassifier(n_estimators=a,criterion=b,min_samples_split=c)
   - a = _randint(50, 150)
   - b = _randchoice(['gini', 'entropy'])
   - c = _randuniform(0.0, 1.0)
- LogisticRegression(penalty=a, tol=b, C=float(c), solver='liblinear')
   - a=_randchoice(['l1','l2'])
   - b=_randuniform(0.0,0.1)
   - c=_randint(1,500)
- MultinomialNB(alpha=a)
   - a=_randuniform(0.0,0.1)
- KNeighborsClassifier(n_neighbors=a, weights=b, p=d, metric=c)
   - a = _randint(2, 25)
   - b = _randchoice(['uniform', 'distance'])
   - c = _randchoice(['minkowski','chebyshev'])
   - if c=='minkowski': d=_randint(1,15)  else:  d=2

**Comment by timm** [comment]
make this into table4 of https://arxiv.org/pdf/1805.00336.pdf

**Comment by timm** [comment]
convert everything to tile charts (using stats.py) which gives you the statistical results

**Comment by timm** [comment]
need popt20

**Comment by timm** [comment]
termination graphs (x-axis = #evaluation), y-axis = improvement (each iteration iqr)

**Comment by timm** [comment]
redo all the results  from both FFT  papers

**Comment by timm** [comment]
consider the problem of tabu search across a wide range.
