### ISSUE TITLE
AUC of D2h (lower the better)

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#5]
- 20 repeats
- lower the better

## camel
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/camel_auc.png)

## Jedit
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/jedit_auc.png)

## Poi
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/poi_auc.png)

## log4j
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/log4j_auc.png)

## synapse
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/synapse_auc.png)

## velocity
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/velocity_auc.png)

## xalan
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/xalan_auc.png)

## xerces
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/xerces_auc.png)

## ivy
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/ivy_auc.png)

## lucene
![file](https://github.com/ai-se/e-dom/raw/master/results/d2h/lucene_auc.png)

**Comment by timm** [comment]
fyi0 these should be drawn on same y-axis 

also, the other thing that needs reporting is the stats tests between these populations

please redo in my xtiles formats so we can get stats. 

![image](https://user-images.githubusercontent.com/29195/46233392-66833c00-c340-11e8-9715-e82f48d64643.png)

**Comment by timm** [comment]
and am I reading this right? I the majority case 6/10, no evidence of improvement below epsilon = 0.1?

but tare are many examples where less is better? needs states to check if there is an issue here

and we need to see in text around each plot the values scored with FFT

**Comment by amritbhanu** [comment]
I see 3/10 where no evidence of improvement below epsilon=0.1

Will do the stats test next!

**Comment by timm** [comment]
we can say "we can say" all we like. but the stats will convince us

by the way, your #evaluation  results are killer.... providing you are getting as good or better results than our old FFT stuff

**Comment by amritbhanu** [comment]
## Lower the rank better
-

**Comment by timm** [comment]
you using my stats.py for the one? what is the Cohen value here? I ask since some of your "differences" are crazy small. eng in camel medians of 136 and 141  are being scored ranks 1 AND 2

**Comment by amritbhanu** [comment]
cohen=0.3 
medians are less but iqr is big. Also remember these are AUC values which are in general big.

**Comment by timm** [comment]
for these charts, set epsilon to one larger that the smallest detail. e.g at epsilon ==2, 135 and 135 should be different numbers see 135 and 125 will be same ranks buts 135 136 can be different

**Comment by amritbhanu** [comment]
Not sure here, prof. What are you trying to say?

**Comment by timm** [comment]
there is a command line option on stats.py that lets you set epsilon. make it bigger (set it to 2). rerun the above. get the ascii charts. paste them in

**Comment by amritbhanu** [comment]
## Lower the rank better!
- based on your suggestion, epsilon is set to 2.

![d2h_auc](https://user-images.githubusercontent.com/3458568/46366589-7012e980-c649-11e8-94d5-c7f2a4d56439.png)
