### ISSUE TITLE
Result - popt20 - Higher the better

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#7]

**Comment by amritbhanu** [comment]
## Median and IQR for 20 repeats in each iteration

### camel
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/camel_iqr.png)

### Jedit
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/jedit_iqr.png)

### Poi
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/poi_iqr.png)

### log4j
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/log4j_iqr.png)

### synapse
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/synapse_iqr.png)

### velocity
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/velocity_iqr.png)

### xalan
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/xalan_iqr.png)

### xerces
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/xerces_iqr.png)

### ivy
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/ivy_iqr.png)

### lucene
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/lucene_iqr.png)

**Comment by timm** [comment]
holy sh*t. can we get a log transform on the x-axis. I'm see plateaus at iterations< 30. is that true?

is the same for d2h?


this is whacked. imagine what would have to be true to get to n<20 in 

```
n= log(1-c)/log(1-(e^2))
```
when c=0.95 and e=?

|c|e|n|
|-|-|-|
|0.95|0.1|298|
|0.95|0.2|73|
|0.95|0.3|31|
|0.95|0.4|17|

the above table says that e must be 0.3, or as big as 0.4!!!
