### ISSUE TITLE
AUC of Popt20 (Higher the better)

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#8]
- 20 repeats
- higher the better

## camel
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/camel_auc.png)

## Jedit
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/jedit_auc.png)

## Poi
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/poi_auc.png)

## log4j
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/log4j_auc.png)

## synapse
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/synapse_auc.png)

## velocity
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/velocity_auc.png)

## xalan
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/xalan_auc.png)

## xerces
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/xerces_auc.png)

## ivy
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/ivy_auc.png)

## lucene
![file](https://github.com/ai-se/e-dom/raw/master/results/popt20/lucene_auc.png)

**Comment by timm** [comment]
here, clearly 0.2 is too big but after that, no evidence of improvement below 0.1
which means for n= log(1-c)/log(1-(e^2)), our e  = 0.1

please draw using my xtile format. if drawn like the following, then your display for a research paper would be very small. also, you'd get stats results for each epsilon

![image](https://user-images.githubusercontent.com/29195/46233157-ae559380-c33f-11e8-93e8-d86dfbd8dcc7.png)

what happens with executions over time? when are their demonstrable improvements at epsilon= 0.1?

**Comment by amritbhanu** [comment]
## Higher the rank better
-

**Comment by timm** [comment]
you using my stats.py for the one? what is the Cohen value here? I ask since some of your "differences" are crazy small. eng in poi medians of 742 are being scored ranks 2 AND 3

t

**Comment by amritbhanu** [comment]
using your stats.py,
cohen=0.3
median is 742 but check the iqr for that.

**Comment by timm** [comment]
here to, set epsilon to 2

**Comment by amritbhanu** [comment]
## Higher the rank better!
- Epsilon set to 2

![popt20_auc](https://user-images.githubusercontent.com/3458568/46366638-9afd3d80-c649-11e8-80e3-cd631a874286.png)
