### ISSUE TITLE
FFT against Tabu

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/e-dom#9]
- Tabu search is showing median of 20 repeats achieved maximum on popt20
- Tabu search is showing median of 20 repeats achieved minimum on d2h

## Max Popt
![max_popt median](https://user-images.githubusercontent.com/3458568/46311677-fc150a80-c590-11e8-99d3-6e53ba945f72.png)

## Min d2h
![min_d2h median](https://user-images.githubusercontent.com/3458568/46311683-ff0ffb00-c590-11e8-93c9-e4b640113020.png)

**Comment by timm** [comment]
how are you computing "same"?

**Comment by amritbhanu** [comment]
within 1% range are termed as same
